### ISSUE TITLE
dynamic text field

### ISSUE THREAD

**Issue by rajeshswain** [Mottie/Keyboard#174]
Dear sir,
This virtual keyboard is not working in dynamically  created text field .
 Can u give some solution for me .

**Comment by udayalakshmi** [comment]
Hi Mottie,

I want to show button with text before the preview input field.
How to show the clear icon inside the preview field.
Thanks in advance

**Comment by Mottie** [comment]
Hi @udayalakshmi!

You can use the `visible` callback function to add content to the keyboard ([demo](http://jsfiddle.net/egb3a1sk/924/)):

```css
.test {
    float: left;
    margin-right: 3px;
}
.ui-keyboard-preview { 
    float:left;
    width: 85%; /* set to 99% in css */
}
.ui-keyboard-preview-wrapper:after {
    content: '';
    position: absolute;
    right: 23px;
    width: 19px;
    height: 13px;
    background: url(http://mottie.github.com/Keyboard/docs/css/images/keyboard.png);
}
```

```js
$('#keyboard').keyboard({
    visible: function (e, keyboard, el) {
    	$('<button type="button" class="test">Test</button>')
        	.click(function(){
        		keyboard.insertText('test');
            	return false;
        	})
        	.insertBefore( keyboard.$preview );
    }
});
```

**Comment by udayalakshmi** [comment]
Thanks for your quick response Mottie.

Can you please share code for showing cancel button inside input field.

Similar to <input type="search" id="keyboard">

I have seen in some demo but now it's deprecated.
 
Can you please share the code to achieve the functionality

**Comment by Mottie** [comment]
Oh, that's the icon you wanted... try [this demo](http://jsfiddle.net/egb3a1sk/926/):

```css
.test {
    float: left;
    margin-right: 3px;
}
.ui-keyboard-preview { 
    float:left;
    width: 85%; /* set to 99% in css */
    padding-right: 10px; /* leave room for "X" */
}
/* hide existing cancel button */
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button {
    -webkit-appearance: none;
}
/* hide added cancel button */
span.clear {
    display: none;
}
/* Only show cancel button when focused */
.focused span.clear {
    position: relative;
    left: -18px;
    display: inline-block;
    font-size: 0.9em;
    font-weight: bold;
    cursor: pointer;
    z-index: 10;
}
/* Add a hover color */
.focused span.clear:hover {
    color: red;
}
```

```js
$('#keyboard').keyboard({
    visible: function (e, keyboard, el) {
    	$('<button type="button" class="test">Test</button>')
        	.click(function(){
        		keyboard.insertText('test');
            	return false;
        	})
        	.insertBefore( keyboard.$preview );

        if ( keyboard.$preview.attr('type') === 'search' ) {
		    keyboard.$preview
                .on('focus blur', function(e){
			        $(this).parent().toggleClass('focused', e.type === 'focus' );
    			})
                .parent()
            	.append('<span class="clear">x</span>')
    			.find('span.clear')
    			.on('click', function(){
        			keyboard.$preview.val('');
    			});
        }
    }
});
```
