### ISSUE TITLE
Positioning Keyboard

### ISSUE THREAD

**Issue by ExtremelySeriousChicken** [Mottie/Keyboard#369]
Hey I am using keyboard js for my webapplication. I want to make my keyboard to be positioned directly below the text. How can I do that? I have been modifying the "position" element in the keyboard, but to no avail. Hope yo can help! Thanks

My Current configuration:

```js
position:{
   my: "bottom",
   at: "center",
   of: "The text element"
}
```

**Comment by Mottie** [comment]
Hi @ExtremelySeriousChicken!

The `position` option is used by [jQuery UI's position utility](http://jqueryui.com/position/). It is an *optional* dependency used to position, and reposition the keyboard if the browser window is resized. So, jQuery UI position utility needs to be loaded before that `position` option will do anything.

Alternatively, you could position the keyboard yourself. [Here is example](http://jsfiddle.net/Mottie/egb3a1sk/493/) that positions the keyboard at the bottom of the browser window using plain css:

```css
.ui-keyboard {
  border-radius: 0;
  left: 0;
  top: auto;
  bottom: 0;
  position: fixed;
  width: 100%;
}
```
