### ISSUE TITLE
Media query cannot resize input field

### ISSUE THREAD

**Issue by dbpalan** [Mottie/Keyboard#396]
I was trying to make a full screen large keyboard with media query.  Every component enlarged except the round corner rectangle box surrounding the textbox.  As a result, the input text only shows the upper half.  Is there anyway to enlarge the surrounding round corner rectangle box of the textbox?  Thanks.

Keyboard code:

    $(function(){
        $('#test').keyboard({
            position: {
                of: $(window),
                my: 'center center',
                at: 'center center',
                at2: 'center center'
            }
        });
    });

Media query code:

    @media all and (min-width: 640px) and (max-width: 1280px) {
    .ui-keyboard div { font-size: 39px; }
    .ui-keyboard .ui-keyboard-input { font-size: 42px; }
    .ui-body .ui-btn { margin: 0; font-size: 10px; }
    .ui-body .ui-keyboard-button { height: 2em; }
    .ui-body .ui-btn-inner { height: 2em; padding: 0.5em 0; }
    }

**Comment by Mottie** [comment]
Hi @dbpalan!

The `.ui-keyboard-input` selector targets the original input.

If you are have `usePreview` set to `true` (default setting), then to target that input, the selector is `.ui-keyboard-preview`.

Try this ([demo](http://jsfiddle.net/egb3a1sk/851/)):

```css
@media all and (min-width: 640px) and (max-width: 1280px) {
.ui-keyboard div { font-size: 39px; }
.ui-keyboard .ui-keyboard-preview { font-size: 42px; border-radius: .3em; background-clip: padding-box; text-indent: .3em; outline: none; }
.ui-body .ui-btn { margin: 0; font-size: 10px; }
.ui-body .ui-keyboard-button { height: 2em; }
.ui-body .ui-btn-inner { height: 2em; padding: 0.5em 0; }
}
```

Yes. I know removing the outline is bad form, but when everything is that large, the outline without a rounded corner is quite unappealing.

**Comment by dbpalan** [comment]
Thanks Mottie, your demo works great while applying to my page still has same issue.  After try and error found that is due to using with bootstrap3 "form-control" class in the "input" tag.

    <div class="input-group input-group-lg">
        <input id="wifissid" type="text" class="form-control">
    </div>

Once applied "form-control" class, the height of the keyboard input field is fixed.  ui-keyboard-preview class seems cannot override the "fix height" properties inherited from the "form-control" class.

**Comment by Mottie** [comment]
The css needs more [specificity](http://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/) than the Bootstrap definitions. Try something like this ([demo](http://jsfiddle.net/MK947/4082/)):

```css
@media all and (min-width: 640px) and (max-width: 1280px) {
    .ui-keyboard div, .ui-keyboard.dropdown-menu {
        font-size: 39px;
    }
    .ui-keyboard .ui-keyboard-preview {
        font-size: 42px;
        border-radius: .3em;
        background-clip: padding-box;
        text-indent: .3em;
        outline: none;
        height: 2em;
    }
    .ui-body .ui-btn {
        margin: 0;
        font-size: 10px;
    }
    .ui-keyboard .btn {
        font-size: 1em;
    }
    .ui-body .ui-keyboard-button {
        height: 2em;
    }
    .ui-body .ui-btn-inner {
        height: 2em;
        padding: 0.5em 0;
    }
}
```
