### ISSUE TITLE
Mathquill for input area

### ISSUE THREAD

**Issue by zagannath** [Mottie/Keyboard#423]
Hi Rob thank you for awesome keyboard  really appreciate  you work,Im wondering is it possible to input laTex expression in your text field by enabling mathquill(https://github.com/mathquill/mathquill).

**Comment by Mottie** [comment]
Hi @zagannath!

You can set the `usePreview` option to `false` to not include a textarea in the keyboard popup.

I created [this demo](http://jsfiddle.net/Mottie/egb3a1sk/1102/) showing how to use virtual keyboard events to update mathquill renders. I hope that is what you had in mind!

HTML
```html
<textarea id="keyboard"></textarea>
<br>
<div id="mathquill"></div>
```

CSS

```css
/* position keyboard at bottom of the screen - jQuery UI isn't even loaded! */
.ui-keyboard {
  border-radius: 0;
  left: 0;
  top: auto;
  bottom: 0;
  position: fixed;
  width: 100%;
}
```

Script

```js
$(function() {

  var mathquill = $('#mathquill').mathquill();

  $('#keyboard')
    .on('visible keyboardChange hidden', function(e, keyboard, el) {
      mathquill.mathquill('latex', keyboard.$preview.val());
    })
    .keyboard({
      usePreview: false
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

});
```

I actually think it would be really cool to make a custom layout which has predefined latex keys like `\frac` and `\sqrt`, etc; but I don't have time to set up a demo like that :wink:

**Comment by zagannath** [comment]
Thank you very much Rob for quick reply ,is it possible to add image on keyboard buttons as I need fraction symbol(2 boxes separated by a line) which is not in unicode charmap.
eg
![screen shot 2016-01-12 at 2 22 57 pm](https://cloud.githubusercontent.com/assets/2561440/12258775/26781542-b937-11e5-88b9-4a0b926dc8c0.png)

**Comment by Mottie** [comment]
To add images, set a background image on the span inside the button. You'll also need to hide the text and set a width to maintain the span's width ([demo](http://jsfiddle.net/Mottie/egb3a1sk/1113/)):

```css
.ui-keyboard-frac span {
  background-image: url(https://cloud.githubusercontent.com/assets/2561440/12258775/26781542-b937-11e5-88b9-4a0b926dc8c0.png);
  background-position: -10px -5px;
  text-indent: -99em;
  width: 1.2em;
}
.ui-keyboard-sqrt span {
  background-image: url(https://cloud.githubusercontent.com/assets/2561440/12258775/26781542-b937-11e5-88b9-4a0b926dc8c0.png);
  background-position: -203px -5px;
  text-indent: -99em;
  width: 1.2em;
}
```

Script with 2 basic action keys

```js
$(function() {

  $.extend($.keyboard.keyaction, {
    'frac': function(kb) {
      kb.insertText('\\frac{}{}');
      var caret = $.keyboard.caret(kb.$el);
      kb.saveCaret(caret.start - 3, caret.start - 3);
    },
    'sqrt': function(kb) {
      kb.insertText('\\sqrt{}');
      var caret = $.keyboard.caret(kb.$el);
      kb.saveCaret(caret.start - 1, caret.start - 1);
    },
  });

  var mathquill = $('#mathquill').mathquill();

  $('#keyboard')
    .on('visible keyboardChange hidden', function(e, keyboard, el) {
      mathquill.mathquill('latex', keyboard.$preview.val());
    })
    .keyboard({
      usePreview: false,
      layout: 'custom',
      customLayout: {
        'default': [
          'sin cos tan \u03c0 {b}',
          '7 8 9 + -',
          '4 5 6 * {frac}',
          '1 2 3 ^ sqrt',
          '0 . , {left} {right}',
          '< > = {clear} {a}'
        ]
      },
      useCombos: false
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

});
```
