### ISSUE TITLE
Zoom Problem

### ISSUE THREAD

**Issue by bliet** [Mottie/Keyboard#484]
The normal behavior of IE11 and Edge is to Zoom in by a Double Tap. 
That is a problem because you cannot type fast on the OSK. Is there a way to solve this issue?

**Comment by Mottie** [comment]
Hi @bliet!

I haven't tried this, but I [read here](http://answers.microsoft.com/en-us/ie/forum/ie10-windows_rt/how-do-you-disable-double-tap-on-the-screen/023b21b5-e516-4922-a5ee-c8937a17895c?page=2) that you'll need to create a css file with the following:

```css
body {
  -ms-touch-action: manipulation !important;
}
```

Then add that file as a user style sheet in Tools &rarr; Internet Options &rarr; Accessibility.

I haven't tried adding the css to the page or directly to the keyboard yet, but I'm in a hurry this morning.

**Comment by bliet** [comment]
I cannot use a solutions, which the user have to change in his internet options. 

I tried this in my code:
```
.ui-keyboard div {
  -ms-touch-action: manipulation !important;
}
```

and this:
```
body {
  -ms-touch-action: manipulation !important;
}
```

It doesn't work. 
I am using hammer.js on other objects. There the double tab doesn't fired a zoom.

**Comment by Mottie** [comment]
Hmm, so I read somewhere else that IE10 and IE11 are different LOL

And please try targeting the keyboard elements, not the divs inside:

```css
.ui-keyboard {
    -ms-touch-action: manipulation; /* IE10  */
    touch-action: manipulation;     /* IE11+ */
}
```

Also, try adding a meta tag to disable zooming:

```html
<meta name="viewport" content="width=device-width, user-scalable=no">
```

Either way, I will likely add options to allow setting your own keybinding as I think the best method would be to use [PEP](https://github.com/jquery/PEP/).
