### ISSUE TITLE
Enlarging text in buttons, equal button size

### ISSUE THREAD

**Issue by tobiasvandriessel** [Mottie/Keyboard#503]
How would I go about enlarging the text in buttons, without changing the size of the button itself?

**Comment by Mottie** [comment]
Hi @tobiasvandriessel!

The keyboard is styled using CSS.

The button `min-width` is set using `em` measurements. So you'll need to modify that and add a `width` set using pixels. The text is containing inside a `<span>` so you can target that element to change the font size ([demo](http://jsfiddle.net/Mottie/egb3a1sk/2150/)).

```css
.ui-keyboard-button {
  height: 30px;
  width: 30px;
}
/* keys with more than one character inside */
.ui-keyboard-widekey {
  height: 30px;
  width: 45px;
}
.ui-keyboard-button span {
  font-size: 1.2em;
}
```

The button has an `overflow: hidden;` set on it, so you might need to make a custom layout using symbols
