### ISSUE TITLE
Darken background on opening keyboard

### ISSUE THREAD

**Issue by exyoris** [Mottie/Keyboard#534]
Hey, I guess my request is a bit of a CSS type, but I can't come up with a solution.
Basically, I would like to darken the whole background or blur it and the focus of the user to be entirely on the keyboard.

Here is what I'm working on: [calculator](http://nationalpalace.bg/witte/html/plneni_adv.html)

Any ideas? Thank you!

**Comment by Mottie** [comment]
Hi @exyoris!

Try something like this ([demo](https://jsfiddle.net/Mottie/3fwyr7s5/)):

CSS

```css
body.overlay-active:after {
  content: ' ';
  width: 100%;
  background: rgba(0, 0, 0, 0.3);
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```

Script

```js
$(function() {

  $('#keyboard')
  	.keyboard({
  		visible: function() {
      	$('body').addClass('overlay-active');
      },
      hidden: function() {
      	$('body').removeClass('overlay-active');
      }
  	});

});
```
