### ISSUE TITLE
Replace label on key

### ISSUE THREAD

**Issue by oz1cz** [Mottie/Keyboard#555]
Is there any way to replace the label on a character key with an image?

I'm trying to create a classical Hebrew keyboard, and some of the vowel characters are so small that they are almost impossible to view in any reasonable font size. So for some of those characters, I would like to display a small image on the key button instead of the actual character.

Is this possible with the current code?

**Comment by Mottie** [comment]
Hi @oz1cz!

There are two ways to add an image to the key...

Add a background image to the specific key. In this example, the `α` (alpha) key is targeted using it's unique class name based on it's **decimal** [ascii value](http://www.fileformat.info/info/unicode/char/03b1/index.htm) (`945`, also known as `03B1` in hex):

```css
/* target greek letter alpha */
.ui-keyboard-945 span {
  /* keyboard icon used in this example */
  background: url(css/images/keyboard.png) center center no-repeat;
  display: block;
  width: 30px;
  /* hide key text */
  text-indent: -999em;
}
/* needed for inline image (second method below) */
.ui-keyboard-button {
  vertical-align: middle;
}
```

And a second, bit more complex method - I really need to fix it - is to make an action key, then set the `display` value to be an image.

**I just found out that including `http://` in the image URL breaks the url inside the image, so I'll need to fix that in the next update.**

```js
// making an action key, it needs an action
$.keyboard.keyaction['β'] = 'β';

$('#keyboard2').keyboard({
  layout: 'custom',
  customLayout: {
    // wrap the key in curly brackets to make it
    // an action key
    'default': ['α {β}']
  },
  display: {
    // including a colon in the url breaks the image :(
  	'β': '<img src="css/images/keyboard.png">'
  }
});
```

**Comment by oz1cz** [comment]
Thank you, @Mottie, the CSS-based solution works very nicely for me!

(Using "text-indent: -999em" to hide the original key text was an eye-opener. :-) )

**Comment by andrewvharris** [comment]
Thanks for this. Unfortunately I am not knowledgeable enough to be able to make this work.

**Comment by Mottie** [comment]
Hi @andrewvharris!

Did you look at the demo from my first response? Adding an image in the display doesn't work correctly, but adding it as a background image in CSS will work. Where are you having issues? If the background image is too big, you may not see it, be sure to include a [`background-size: cover`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) to shrink it down.

**Comment by andrewvharris** [comment]
Hello Rob

The link you sent me (http://jsbin.com/pawiyejupi/edit?html,output) looks much more understandable to me and is really helpful so thank you very much for that. I changed the key letters to musical symbols by cutting and pasting in from the Unicode library on Wikipedia. Is it possible to map the output of a key so that for example pressing one that shows [quarter rest] <https://en.wikipedia.org/wiki/File:QuarterRest.svg>  on the key will produce "z1" in the textarea?

Thanks again for your help with this, I'm learning fast

Andrew

[http://static.jsbin.com/images/logo.png]<http://jsbin.com/pawiyejupi/edit?html,output>

JS Bin<http://jsbin.com/pawiyejupi/edit?html,output>
jsbin.com
A live pastebin for HTML, CSS & JavaScript and a range of processors, including SCSS, CoffeeScript, Jade and more...




Andrew Harris


________________________________

**Comment by Mottie** [comment]
In [this example](http://jsfiddle.net/egb3a1sk/4379/), we'll add an action key named `{halfQuarter}` (name it anything you want, but use the same name throughout the JavaScript and CSS). 

1. First we'll define the key action
2. Then add it to the `customLayout` as `{halfQuarter}`
3. Set it's display to a space
4. Define the background image in the css:
  - I clicked on the half quarter svg image on the wikipage and was taken to a page with only the svg showing.
  - Then go to https://dopiaza.org/tools/datauri/index.php, click on "Retrieve file from a URL" radio option.
  - Leave "Use base64 encoding" checked.
  - Click on "Generate Data URI".
  - Copy the data URI from the resulting input.
  - Paste the data URL inside the quotes of `background-image: url('')` in the CSS

```js
$(function() {

	$.keyboard.keyaction.halfQuarter = 'z1';

  $('#keyboard').keyboard({
      layout: 'customLayout',
      customLayout: {
        'default': [
          '{halfQuarter}'
        ]
      },
      display: {
        'halfQuarter': ' '
      }
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });

});
``` 

CSS

```css
.ui-keyboard-halfQuarter span {
  width: 20px;
  height: 20px;
  display: inline-block;
  background-repeat: no-repeat;
  background-position: center center;
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhLS0gQ3JlYXRlZCB3aXRoIElua3NjYXBlIChodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy8pIC0tPgo8c3ZnCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgdmVyc2lvbj0iMS4wIgogICB3aWR0aD0iMTIiCiAgIGhlaWdodD0iMjUiCiAgIGlkPSJzdmcxMzYxIj4KICA8ZGVmcwogICAgIGlkPSJkZWZzMTM2MyIgLz4KICA8ZwogICAgIGlkPSJsYXllcjEiPgogICAgPGcKICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNzUuNzE5LC01NzIuMDA1KSIKICAgICAgIHN0eWxlPSJmaWxsOiMwMDAwMDA7ZmlsbC1vcGFjaXR5OjEiCiAgICAgICBpZD0iZzMwMDgiPgogICAgICA8cGF0aAogICAgICAgICBkPSJNIDE4MS42OTkwOSw1ODguNzYzOTggQyAxODIuNDczNjIsNTg5LjA4OTg4IDE4Mi4zNzk3LDU5MC40NjQ4MSAxODEuNDIzNzEsNTg5LjgwMjYxIEMgMTgwLjcwNjQ0LDU4OC45MTM1NCAxNzkuMzM4MzEsNTg4LjE0NDgxIDE3OC4zNDA5Myw1ODkuMTExNTUgQyAxNzcuNTEzOSw1ODkuODc3NiAxNzcuNzg2OTQsNTkxLjI3MDIzIDE3OC43MTYwOSw1OTEuODE1MDkgQyAxNzkuMzcwNDQsNTkxLjk0ODkzIDE3OS44NjczMiw1OTMuMDU3MDQgMTc4Ljc5NTE4LDU5Mi42NDIgQyAxNzcuMjUwMTUsNTkyLjExNTQzIDE3NS42MDA2Miw1OTAuNzkxNzYgMTc1LjcyNTcsNTg4Ljk5OTg1IEMgMTc1LjcwMjYxLDU4Ny43Nzg3IDE3Ni45NTc3LDU4Ny4wMjE3NSAxNzguMDcyMDksNTg3LjEwNiBDIDE3OC41MjAxMyw1ODYuOTQ1NTUgMTc5Ljc1ODI0LDU4Ny41ODYzMiAxNzkuNzAyNTEsNTg3LjMwMjUzIEMgMTc4Ljk0OTIxLDU4Ni4xNDU1MyAxNzguMDg5NTcsNTg1LjA1MTI2IDE3Ny40MTUwOSw1ODMuODQ3NjIgQyAxNzcuMTc2NjEsNTgzLjEyMDc4IDE3Ny42OTk0Miw1ODIuNDI5MDUgMTc3LjkxOTksNTgxLjc1MDIgQyAxNzguMzk5NjcsNTgwLjU1MzEzIDE3OC45MzYzNiw1NzkuMzc2NTEgMTc5LjM3NDA5LDU3OC4xNjQzOCBDIDE3OS40MTUyNSw1NzcuNDE4MDEgMTc4Ljc1MjQ5LDU3Ni44ODkxMiAxNzguNDA5MTQsNTc2LjI3NzIgQyAxNzguMDExNTMsNTc1LjY0MzM0IDE3Ny40OTE2OSw1NzUuMDczMDkgMTc3LjIwMjA5LDU3NC4zODIyNSBDIDE3Ny4yMjIyNSw1NzMuNTA0NTUgMTc4LjEzMDEyLDU3NC40ODU5NiAxNzguMzc2MzcsNTc0Ljg0MzkzIEMgMTc5LjQ1MDM2LDU3Ni4xMTgzMiAxODAuNTc5NDUsNTc3LjM0OTA2IDE4MS42MTUwOSw1NzguNjUzODMgQyAxODIuMzA3NDksNTc5LjQ5NzMgMTgxLjY2MTU4LDU4MC40ODUyNSAxODEuMzI1ODEsNTgxLjMyNzM0IEMgMTgwLjgyNzM1LDU4Mi41ODMwOSAxODAuMTkwMzMsNTgzLjc5MTY3IDE3OS44MjQwOSw1ODUuMDkzMjMgQyAxNzkuNzc2MzksNTg2LjE2NDYgMTgwLjU2MDMsNTg3LjA1MTg1IDE4MS4wNjM0Niw1ODcuOTQwNjIgQyAxODEuMjU2ODUsNTg4LjIyODgzIDE4MS40NzI4Miw1ODguNTAxMTIgMTgxLjY5OTA5LDU4OC43NjM5OCB6ICIKICAgICAgICAgc3R5bGU9ImZpbGw6IzAwMDAwMDtmaWxsLW9wYWNpdHk6MSIKICAgICAgICAgaWQ9InBhdGgzMDEwIiAvPgogICAgPC9nPgogIDwvZz4KPC9zdmc+Cg==');
}
```

**Comment by andrewvharris** [comment]
Hello Rob

The example<http://jsfiddle.net/egb3a1sk/4379/> you sent is exactly it. So if I may ask one last (probably pretty dumb question) before I leave you alone and make it work. In order to get this to work I will need to upload and extract all the dependencies from the Mottie Keyboard depository into a directory and then make sure that the html page I generate points to them. The code from each area of the example you linked (the CSS, HTML and Java) then all go in that html page inside the correct tags ?

Thanks for your patience and help. I will be able to achieve what I am now trying to get done thanks to you

All the best

Andrew


Andrew Harris


________________________________

**Comment by Mottie** [comment]
> The code from each area of the example you linked (the CSS, HTML and Java) then all go in that html page inside the correct tags ?

Yes. But this is JavaScript. Java is a completely different language.

You don't really need to download all the files unless you plan to use it offline; but if you want, the whole package isn't that big. Download the [zip file](https://github.com/Mottie/Keyboard/archive/master.zip) of the current build, extract and save the files to your hard drive somewhere. Then, make sure to point to the necessary files in the HTML. You'd need to repeat this process for any updates.

If you're planning on using the files online, then I would recommend pointing the js and css to [cdnjs](https://cdnjs.com/libraries/virtual-keyboard) - it's a [content delivery network](https://en.wikipedia.org/wiki/Content_delivery_network) so it will provide the needed files quickly. You'll need to manually change the links for any updates.

**Comment by Mottie** [comment]
I just made a change, not on the CDN yet, that will allow you to add an `<img>` inside the display option, so you won't need to add the images as a background:

```js
display: {
  'halfQuarter': '<img src="https://upload.wikimedia.org/wikipedia/commons/0/03/QuarterRest.svg">'
}
```

You'll need to tweak the css a bit to get stuff to line up ([demo](http://jsfiddle.net/Mottie/egb3a1sk/4398/)). Also, I wouldn't recommend using that wikimedia url if you're planning on making the program work offline.

**Comment by Mottie** [comment]
Version 1.28.2 has been released with this change. It should be available on CDNJS soon.

**Comment by andrewvharris** [comment]
It works brilliantly. Thank you so much

**Comment by andrewvharris** [comment]
Hello Rob.

I am so very close but have encountered one issue in terms of the keyboard events not being interpreted by the abc notation script. You can see what I mean here

http://truro-penwith.000webhostapp.com/new1.html


As you can see the text box is written into my the keyboard, but the notes dont appear until you either add  a letter from the physical keyboard or click with the mouse on the music. I have pasted the html below.

Any ideas?

Thanks

Andrew



<!DOCTYPE html>
<html lang="en">
  <head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet' type='text/css'>
<link href="style.css" rel="stylesheet" type="text/css" />
<script src="/abcjs_editor_2.0-min.js" type="text/javascript"></script>
</head>
<body>


<div class="col-sm-1" id="editwindow" style="margin: 0px; white-space: nowrap; min-width:700px;">

<textarea name="keyboard" id="keyboard" rows="20" cols="46" style="padding:5px; margin: 0px;">
X: 1
T: Cooley's
M: 4/4
L: 1/8
R: reel
K: Emin
|ddd|
</textarea>
<span id="paper0"></span>
</div>



<script type="text/javascript">
function do_resize() {
var w = $('#topbar').width();
var e = $('#keyboard').width();
//console.log("w = " + w);
//console.log("e = " + e);
var sw = 700;
var scale = 0.85;
var arealeft = w - e;
console.log("arealeft = " + arealeft);
if (arealeft < 800) {
scale = scale * (arealeft - 50)/ sw;
sw = arealeft - 50;
//console.log("scale = " + scale);
//console.log("sw = " + sw);
}
$('#paperid').width = sw;
abc_editor = new ABCJS.Editor("keyboard", { paper_id: "paper0", midi_id:"midi", warnings_id:"warnings",
render_options: {staffwidth: sw, scale: scale},
midi_options: {program: 2,
qpm: 150, type: "qt"},
gui: false });
$('#paperid').width = sw;
$('#bluebox').width = sw;
};

window.onresize = function(event) {
do_resize();
};

window.onload = function() {
do_resize();
}
</script>
</div>


<div id="wrap">


  <textarea id="keyboard"></textarea>
</div>

<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
<script src="https://mottie.github.io/Keyboard/js/jquery.keyboard.js"></script>
<script src="https://mottie.github.io/Keyboard/js/jquery.keyboard.extension-typing.js"></script>
<script>


/* VIRTUAL KEYBOARD DEMO - https://github.com/Mottie/Keyboard */
$(function() {

  $('#keyboard').keyboard({
      layout: 'custom',
      customLayout: {
        'default': [
          'a b c d e f g #',
          'A B C D E F G _',
          '7 8 9 ~ = " \' /',
          '4 5 6 | [ ] ( )',
          '1 2 3 > z , . :',
          '0 {space} {meta1} {b} {e}'
        ],

      },
      usePreview: false,
      autoAccept: true,
      display: {
      'default': '\u{1d11e}:ABC_Music_Notation',
        'meta1': 'ABC:Standard_Keyboard'
      }
    })
    // activate the typing extension
    .addTyping({
      showTyping: true,
      delay: 250
    });
});

  </script>
</body></html>




Andrew Harris


________________________________

**Comment by Mottie** [comment]
Within in the keyboard initialization, add a [`change` callback](https://github.com/Mottie/Keyboard/wiki/Methods#change) which calls the `do_resize()` function ([demo](https://jsbin.com/nawiqor/edit?html,output)):

```js
change: function () {
  do_resize();
}
```

**Comment by andrewvharris** [comment]
Thank you very much


Andrew Harris


________________________________

**Comment by andrewvharris** [comment]
Hello Rob

What function creates the text box above the keyboard? I want to turn it of so that the keyboard keeps typing into the original text box.

Many thanks

]Andrew

http://truro-penwith.000webhostapp.com/musickb.html


Andrew Harris


________________________________

**Comment by Mottie** [comment]
Set the [`usePreview` option](https://github.com/Mottie/Keyboard/wiki/Usability#usepreview) to `false`.

**Comment by andrewvharris** [comment]
Hello Rob

I thought you might like to see how the music typing is coming together. It is very excitingly working very well. I've just got to figure out now how to take the contents of the text area and compare it against a correct version, which is not something I will bother you with unless you have any genius ideas

Cheers

Andrew

http://truro-penwith.000webhostapp.com/test.html


Andrew Harris


________________________________

**Comment by andrewvharris** [comment]
Dear Rob

I am ready to start testing the music resource I have put together using your keyboard and ABC notation.

http://truro-penwith.000webhostapp.com/final.html


I just want to know that as far as I understand in theory I should be able to style the keyboard so that it, in fact, looks like a piano keyboard? It would only be a question of spacing as I could have the top row being the black keys and the one underneath, the white. Is this detailed in the styling part of the Wiki (any help gratefully received)

Thanks and all the  best

Andrew

Andrew Harris


________________________________
From: Andrew Harris
Sent: 01 May 2018 17:00
To: Mottie/Keyboard; Mottie/Keyboard
Cc: Mention
Subject: Mottie Music Keyborad


Hello Rob

I thought you might like to see how the music typing is coming together. It is very excitingly working very well. I've just got to figure out now how to take the contents of the text area and compare it against a correct version, which is not something I will bother you with unless you have any genius ideas

Cheers

Andrew

http://truro-penwith.000webhostapp.com/test.html


Andrew Harris


________________________________

**Comment by Mottie** [comment]
Very nice!

> figure out now how to take the contents of the text area and compare it against a correct version

I think you should check out [this code](https://codereview.stackexchange.com/a/133849/9882) which checks and highlights the difference between two strings.

> style the keyboard so that it, in fact, looks like a piano keyboard?

Yes, I have [this demo](https://jsfiddle.net/Mottie/uw7hmL6q/) on the wiki page that uses css absolute positioning to position the enter key, but in your case I think you could use the css from [beautiful piano](https://github.com/musicjs/beautiful-piano) - [here's a demo](https://jsfiddle.net/qmysop0v/) - but I'm not sure if you're going to include the black keys?

```css
.ui-keyboard-button[class*="-A"],
.ui-keyboard-button[class*="-B"],
.ui-keyboard-button[class*="-C"],
.ui-keyboard-button[class*="-D"],
.ui-keyboard-button[class*="-E"],
.ui-keyboard-button[class*="-F"],
.ui-keyboard-button[class*="-G"] {
  background: linear-gradient(-30deg, #f5f5f5, #fff);
  box-shadow: inset 0 1px 0px #fff, inset 0 -1px 0px #fff, inset 1px 0px 0px #fff, inset -1px 0px 0px #fff, 0 4px 3px rgba(0, 0, 0, 0.7);
  height: 100px;
  position: relative;
  margin: 2px 0 6px;
}

.ui-keyboard-button[class*="-A"]:active:before,
.ui-keyboard-button[class*="-B"]:active:before,
.ui-keyboard-button[class*="-C"]:active:before,
.ui-keyboard-button[class*="-D"]:active:before,
.ui-keyboard-button[class*="-E"]:active:before,
.ui-keyboard-button[class*="-F"]:active:before,
.ui-keyboard-button[class*="-G"]:active:before {
  content: "";
  width: 0px;
  height: 0px;
  border-width: 216px 5px 0px;
  border-style: solid;
  border-color: transparent transparent transparent rgba(0, 0, 0, 0.1);
  position: absolute;
  left: 0px;
  top: 0px;
}

.ui-keyboard-button[class*="-A"]:active:after,
.ui-keyboard-button[class*="-B"]:active:after,
.ui-keyboard-button[class*="-C"]:active:after,
.ui-keyboard-button[class*="-D"]:active:after,
.ui-keyboard-button[class*="-E"]:active:after,
.ui-keyboard-button[class*="-F"]:active:after,
.ui-keyboard-button[class*="-G"]:active:after {
  content: "";
  width: 0px;
  height: 0px;
  border-width: 216px 5px 0px;
  border-style: solid;
  border-color: transparent rgba(0, 0, 0, 0.1) transparent transparent;
  position: absolute;
  right: 0px;
  top: 0px;
}
```

I also cleaned up the `$.keyboard.keyaction` key settings in that demo.
