### ISSUE TITLE
Validate function

### ISSUE THREAD

**Issue by Nitro1977** [Mottie/Keyboard#571]
Hi Mottie,
very very good work$!!

i have a question.......it's possible in the num pad when the parameter "acceptValid: true" to see the "up limit input" e "down limit input"  in the the keyboard......near the input fiield??

Thanks bye,
Nicola

**Comment by Mottie** [comment]
Hi @Nitro1977!

Thanks! 😸

I'm not quite sure what you mean by see the up and down limit near the input field. You mean like a label?

I set up [this demo](http://jsfiddle.net/egb3a1sk/2777/) so you can easily modify it to show me what you mean. Or, at least we are both working with the same example.

**Comment by Nitro1977** [comment]
yes just 2 label to indicate the min & max input limit........

**Comment by Mottie** [comment]
Hmm, something like this [demo](http://jsfiddle.net/Mottie/egb3a1sk/2779/)?

CSS

```css
.msg {
  position: relative;
  z-index: 2;
  cursor: pointer;
}

.msg.error:before {
  position: absolute;
  bottom: 150%;
  left: 50%;
  margin-bottom: 5px;
  margin-left: -80px;
  padding: 7px;
  width: 160px;
  border-radius: 3px;
  background-color: rgba(128, 0, 0, .9);
  color: #fff;
  content: attr(data-tooltip);
  text-align: center;
  font-size: 14px;
  line-height: 1.2;
}
.msg.error:after {
  position: absolute;
  bottom: 150%;
  left: 50%;
  margin-left: -5px;
  width: 0;
  border-top: 5px solid rgba(128, 0, 0, .9);
  border-right: 5px solid transparent;
  border-left: 5px solid transparent;
  content: ' ';
  font-size: 0;
  line-height: 0;
}
```

```js
$(function() {
	var $msg = $('.msg');
  
  $('#keyboard')	.keyboard({
		layout : 'num',
    usePreview: false,
    // Prevent keys not in the displayed keyboard from being typed in
		restrictInput : true,
    // prevent typing in values > 999
    maxLength: 3,
    // activate the "validate" callback function
		acceptValid : true,
    validate: function (keyboard, value, isClosing) {
      var val = parseFloat(value),
      	inRange = val >= 0 && val <= 100;
      if (!inRange) {
        $msg.attr(
        	'data-tooltip',
          val > 100 ? "Enter a value less than 100" : "Enter a positive value < 100"
        );
      }
      $('.msg').toggleClass('error', !inRange);
			return inRange;
		},
    hidden: function() {
    	// hide error once keyboard closes
    	$msg.removeClass('error');
    }
	})
	.addTyping();
});
```
