### ISSUE TITLE
Size of keyboard after clicking shift button

### ISSUE THREAD

**Issue by sohrabhejazi** [Mottie/Keyboard#598]
After clicking shift button, the size of keyboard would be bigger than normal. How to avoid it? I want to have the same size.

**Comment by Mottie** [comment]
Hi @sohrabhejazi!

If you're using a custom layout, there might be an extra key in a row that is changing the width of the keyset.

Action keys (e.g. Accept and Cancel) can be set to their narrow form using the action key abbreviation (`{a}` and `{c}` respectively) - see https://github.com/Mottie/Keyboard/wiki/Layout#action.

Lastly, you can force the key width of each key by setting the width. Something like this:

```css
.ui-keyboard-button:not(.ui-keyboard-widekey) {
  width: 30px;
  height: 30px;
}
```
