### ISSUE TITLE
Button colors not changing on a touch screen

### ISSUE THREAD

**Issue by JosephKigin** [Mottie/Keyboard#710]
Thank you for making such an amazing tool. I really do appreciate how much time and effort you have put towards this.

I wrote a website that uses a custom layout keyboard and I changed the keyboard-basic.css to make the buttons turn blue on-click. This works on my computer with a mouse, but when I try to use the keyboard on a touchscreen the buttons do not change color. I am not sure why this is and was hoping you would have some insight.

This is what I changed in the .css:
.ui-keyboard-button:not([disabled]):active {
		background: #ddd;
		background-image: -webkit-linear-gradient(-90deg, #d3d3d3 0%, #00a1e3 100%);
		background-image: linear-gradient(-90deg, #d3d3d3 0%, #00a1e3 100%);
	}

Thanks in advance,

Joe

**Comment by Mottie** [comment]
Hi @JosephKigin!

Very strange indeed... I would think that the `:active` selector would work. Anyway, a class is added when the key is actively being used. Try this css ([demo](https://jsfiddle.net/Mottie/egb3a1sk/6548/)):

```css
.ui-keyboard-button.ui-state-hover {
  background: #ddd;
  background-image: -webkit-linear-gradient(-90deg, #d3d3d3 0%, #00a1e3 100%);
  background-image: linear-gradient(-90deg, #d3d3d3 0%, #00a1e3 100%);
}
```
