### ISSUE TITLE
Excluding Keys in default Layout

### ISSUE THREAD

**Issue by mouryaamit** [Mottie/Keyboard#718]
Is there a way to exclude specific keys from the default layout without making a custom layout.
Like I would like to exclude only TAB, ENTER and SPACE

**Comment by Mottie** [comment]
Hi @mouryaamit!

Maybe hiding the keys visually would work for you? All that is needed is the following css ([demo](https://jsfiddle.net/Mottie/egb3a1sk/6977/)):

```css
.ui-keyboard-space,
.ui-keyboard-enter,
.ui-keyboard-tab {
  display: none;
}
```
