### ISSUE TITLE
How to open keyboard as modal?

### ISSUE THREAD

**Issue by mKliver** [Mottie/Keyboard#773]
I mean i want to prevent page interaction when keyboard open, like in this demo.
https://www.seanmcquay.com/mok-project/sample-keyboard.htm

This is possible?

**Comment by Mottie** [comment]
Hi @mKliver!

The keyboard already opens as modal. I think what you're asking for is the overlay behind the keyboard. Check out [this demo](https://jsfiddle.net/Mottie/egb3a1sk/7133/)

CSS

```css
html, body {
  position: relative;
  height: 100%;
}

.overlay:after {
  content: ' ';
  width: 100vw;
  height: 100vh;
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  background: #0004;
}
```

JS

```js
$(function() {
  var $body = $('body');
  $('#keyboard').keyboard({
  	stayOpen: true,
  	visible: function() {
    	$body.addClass('overlay');
    },
    hidden: function() {
    	$body.removeClass('overlay');
    }
  });
});
```
