### ISSUE TITLE
退格键 在谷歌浏览器无法正常显示

### ISSUE THREAD

**Issue by lixuguang001** [Mottie/Keyboard#779]
自定义键盘{b} chrome浏览器显示为小尺寸

**Comment by lixuguang001** [comment]
自定义键盘 {b} chrome浏览器显示为小方框

**Comment by Mottie** [comment]
Hi @lixuguang001!

Use the [`display` option](https://github.com/Mottie/Keyboard/wiki/Language#display) to change the character - [demo](https://jsfiddle.net/Mottie/egb3a1sk/7145/)

```js
display: {
  'b': '<:Backspace'
}
```

or use CSS to change the button style

```css
.ui-keyboard-bksp {
  width: 80px;
  height: 80px;
}
```
