### ISSUE TITLE
Add blured background behind keyboard

### ISSUE THREAD

**Issue by GenijeOnline** [Mottie/Keyboard#802]
Hello to all.

Please help me to figure it out, how to make that the page (behind keyboard) goes blur when keyboard is open.
I have this:

```
visible: function() {
      	$('body').addClass('overlay-active');
      },
      hidden: function() {
      	$('body').removeClass('overlay-active');
      }
```
but this only change back page color (add grey overlay).
I would like to add blur to this overlay.

Thanks.

**Comment by Mottie** [comment]
Hi @GenijeOnline!

Try this ([demo](https://jsfiddle.net/Mottie/0qs8pr4v/)):

CSS

```css
.keyboard-modal {
  z-index: 15999;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.3);
}
```

JS

```js
$(function() {
  $('#keyboard').keyboard({
    visible: function(e, keyboard, el) {
      var modal = $('<div class="keyboard-modal"></div>');
      keyboard.$keyboard.before(modal);
      modal.click(function(e) {
        keyboard.accept();
        return false;
      });
    },
    beforeClose: function(e, keyboard, el, accepted) {
      $('.keyboard-modal').remove();
    }
  });
});
```

**Comment by GenijeOnline** [comment]
Nope..it's pretty-much the same effect that I get..it is only overlay.
The thing I want is something like this with
`-webkit-filter: blur(10px);` 
in CSS..but ofcourse blur only backpage (it is html page, not picture) and keep keyboard focused.

![screen2](https://user-images.githubusercontent.com/48319113/109291050-c095cd80-7828-11eb-822e-afba5cd01ec0.jpeg)

**Comment by Mottie** [comment]
Oh, use [`backdrop-filter`](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) - it's not yet supported by all browsers, but [it'll add that blur effect](https://jsfiddle.net/Mottie/acng12je/).

```css
.keyboard-modal {
  z-index: 15999;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  backdrop-filter: blur(4px);
}
```

Note: that `z-index` is based on the bootstrap modal being set to a `z-index` of `16000`.
